#!/bin/sh
#
# Configuring host communication.
#

case "$1" in
start)
printf "Starting Python Web Server"
ps -A

;;
stop)
printf "Shutdowning Python Web Server"

;;
restart)
printf "Restarting Python Web Server"

;;
*)
echo "Error : Python Web Server"

;;	
esac
exit $?