#!/bin/sh
#
# Configuring host communication.
#

case "$1" in
start)
printf "Configuring host communication."
/usr/bin/python /root/simple_http_server.py

[ $? = 0 ] && echo "OK" || echo "FAIL"
;;
stop)
printf "Shutdown host communication. "

[ $? = 0 ] && echo "OK" || echo "FAIL"
;;
restart|reload)
"$0" stop
"$0" start
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac

exit $?
